"""Add quote column

Revision ID: fb1d89ed9b1a
Revises: 
Create Date: 2025-05-02 22:29:24.904352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb1d89ed9b1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('quote', sa.Text(), nullable=True))
    op.drop_column('book', 'needs_cover_review')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('needs_cover_review', sa.INTEGER(), nullable=True))
    op.drop_column('book', 'quote')
    # ### end Alembic commands ###
